/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const VvordleLazyImport = createFileRoute('/vvordle')()
const PokemonRouletteLazyImport = createFileRoute('/pokemon-roulette')()
const BanterLazyImport = createFileRoute('/banter')()
const AboutLazyImport = createFileRoute('/about')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const VvordleLazyRoute = VvordleLazyImport.update({
  path: '/vvordle',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/vvordle.lazy').then((d) => d.Route))

const PokemonRouletteLazyRoute = PokemonRouletteLazyImport.update({
  path: '/pokemon-roulette',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/pokemon-roulette.lazy').then((d) => d.Route),
)

const BanterLazyRoute = BanterLazyImport.update({
  path: '/banter',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/banter.lazy').then((d) => d.Route))

const AboutLazyRoute = AboutLazyImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/banter': {
      id: '/banter'
      path: '/banter'
      fullPath: '/banter'
      preLoaderRoute: typeof BanterLazyImport
      parentRoute: typeof rootRoute
    }
    '/pokemon-roulette': {
      id: '/pokemon-roulette'
      path: '/pokemon-roulette'
      fullPath: '/pokemon-roulette'
      preLoaderRoute: typeof PokemonRouletteLazyImport
      parentRoute: typeof rootRoute
    }
    '/vvordle': {
      id: '/vvordle'
      path: '/vvordle'
      fullPath: '/vvordle'
      preLoaderRoute: typeof VvordleLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  AboutLazyRoute,
  BanterLazyRoute,
  PokemonRouletteLazyRoute,
  VvordleLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/banter",
        "/pokemon-roulette",
        "/vvordle"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/about": {
      "filePath": "about.lazy.tsx"
    },
    "/banter": {
      "filePath": "banter.lazy.tsx"
    },
    "/pokemon-roulette": {
      "filePath": "pokemon-roulette.lazy.tsx"
    },
    "/vvordle": {
      "filePath": "vvordle.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
