name: CI

on:
    push:
        branches: '**'

    workflow_dispatch:

permissions:
    contents: read

jobs:
    ci:
        name: CI
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [22]

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Enable Corepack
              run: corepack enable

            - name: Prepare pnpm@10.2.0
              run: corepack prepare pnpm@10.2.0 --activate

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'pnpm'

            - name: Install dependencies
              run: pnpm install

            - name: Audit dependencies
              run: pnpm audit

            - name: Prettier
              run: pnpm prettier

            - name: Lint
              run: pnpm eslint . --max-warnings 0

            - name: Typecheck
              run: pnpm typecheck --verbose

            - name: Build
              run: pnpm -r build
