name: CI

on:
    workflow_call:
    workflow_dispatch:

permissions:
    contents: read

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [22]

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Update Corepack
              run: npm install -g corepack@latest

            - name: Enable Corepack
              run: corepack enable

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'pnpm'

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Audit dependencies
              run: pnpm audit

            - name: Prettier
              run: pnpm prettier:check

            - name: Lint
              run: pnpm eslint . --max-warnings 0

            - name: Typecheck
              run: pnpm typecheck --verbose

            - name: Build
              run: pnpm -r build

            - name: Upload build artifact
              uses: actions/upload-artifact@v4
              with:
                  name: build-output
                  path: packages/api/dist
