name: CI

on:
    push:
        branches: '**'

    workflow_dispatch:

permissions:
    contents: read

jobs:
    ci:
        name: CI
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [20]

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Enable Corepack
              run: corepack enable

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'pnpm'

            - name: Install dependencies and audit
              run: |
                  pnpm install
                  pnpm audit

            - name: Prettier
              run: pnpm prettier

            - name: Typecheck
              run: pnpm typecheck --verbose && node scripts/build.js --ignore-projects=packages/content

            - name: Lint
              run: DEBUG=eslint:cli-engine pnpm eslint . --max-warnings 0
