name: Publish content

on:
    workflow_call:
    workflow_dispatch:

permissions:
    contents: read

jobs:
    build:
        name: Publish
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [22]

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Update Corepack
              run: npm install -g corepack@latest

            - name: Enable Corepack
              run: corepack enable

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'pnpm'

            - name: Install dependencies
              run: pnpm --filter api --filter content install --frozen-lockfile

            - name: Build API
              run: pnpm --filter api build

            - name: Publish content
              run: pnpm --filter=content compile
