name: Publish content

on:
    workflow_call:
    workflow_dispatch:

permissions:
    contents: read

jobs:
    build:
        name: Publish
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [22]

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Update Corepack
              run: npm install -g corepack@latest

            - name: Enable Corepack
              run: corepack enable

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'pnpm'

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Publish content
              run: pnpm --filter=content compile

            # - name: Upload build artifact
            #   uses: actions/upload-artifact@v4
            #   with:
            #       name: build-output
            #       path: packages/api/dist
